name: todoflutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  table_calendar: ^3.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  synchronized: ^3.0.1
  lunar: ^1.3.1
  intl: ^0.18.0
  flutter_swipe_action_cell: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/
     - images/14.png



